---
  - name: Install repo.zabbix.deb package from the internet.
    apt:
      deb: "https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+{{ ansible_distribution_release }}_all.deb"

  - name: Zabbix-agent is present
    apt:
      name: zabbix-agent
      state: present
      update_cache: yes
    notify: restart-zabix-agent

  - name: Zabbix-agent is latest
    apt:
      name: zabbix-agent
      state: latest
    notify: restart-zabix-agent

